{
 "title": "CPU-Usage",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Http-Request-Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kubelet_http_requests_total{instance=\"minikube\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-CPU-Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{namespace=\"app-stack\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod-Restarts-Count",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_restarts_total{namespace=\"app-stack\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}