apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auth-service-ns
  namespace: app-stack
spec:
  podSelector:
    matchLabels:
      app: auth-service
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: data-service